### PR TITLE
BEP016: Rename "dti" to "tensor"

### PR DESCRIPTION
**Pull request by Lestropie**
I have a particular disdain for the acronym "DTI". It very frequently confounds the process of *imaging* (i.e. obtaining image data) with *model fitting*, and I've seen various uses where it refers to one, the other, or both. I would therefore prefer to avoid it here.

### CODE REVIEW

**Comment by arokem** [comment]
I agree with the general objection. We've used ["DTM"](
https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0123272)
to refer to this model. It's just an acronym of the phrase at the end of
this same sentence.

**Comment by Lestropie** [comment]
First time I've seen "DTM". I immediately think of Deutsche Tourenwagen Masters...

**Comment by arokem** [comment]
Should I tell you what "bs" reminds me of? 😄 

Be as our objections may be, I think that "dti" is a very well-recognized acronym.

**Comment by Lestropie** [comment]
Yeah I know, I've been looking at that one too.

Depending on the outcome of #32, I'm not sure whether to propose "ballsticks", or whether it would actually be more appropriate to have an exceptionally general "discrete / finite mixture model" model, that covers all scenarios of all possible combinations of fibre / non-fibre constituent components (e.g. tensors, zeppelins, isotropic components, etc..). "Ball and sticks" and "NODDI" are just two specific instances of a whole generalised class, and it may be that supporting the generalised class is preferable.

**Comment by francopestilli** [comment]
I support tensor it might, later on, create further discussion related to what we discussed previously: for example whether models such as the tensor should be modality independent or not.

DT = Diffusion Tensor would be specific to this modality
Tensor is more general.

**Pull request merged**
