### PR TITLE
SH description

### PR DESCRIPTION
**Pull request by Lestropie**
Updating description of SH basis based on recent discussions & revisions in *MRtrix3*. I think the equations are necessary in order to summarise the concepts in a small amount of space. It may however be an issue linking to a third-party site in order to generate the images, and instead be preferable to generate the images explicitly and upload them to the repo?

### CODE REVIEW

**Comment by francopestilli** [comment]
@arokem and @francopestilli are looking over this pull request. We are not sure what woudl be the best approach to resolve this pull request. It seems that if this is resolved this BEP is in good shape for a candidate proposal to be reviewed by the broader community. Can @franklin-feingold suggest us how to approach this? CC @oesteban @Lestropie

**Comment by franklin-feingold** [comment]
Perhaps teasing apart a few things:

- Regarding the completion stage - sounds great! if this BEP is at the final stage we'll want to get you scheduled to join a Maintainers Group meeting to discuss the final submission process and timeline (most of that information can be found here: https://github.com/bids-standard/bids-specification/wiki/BIDS-Extension-Proposal-(BEP)-submission-process)
- From the GitHub side - it appears there is a merge conflict on this one, it may be beneficial to get @sappelhoff and @effigies eyes on it prior to getting it in

**Comment by arokem** [comment]
Regarding the merge, shouldn't this be reopened against #6, rather than against the `dwi_derivatives_restructure` branch?

**Comment by Lestropie** [comment]
Regarding specifically the SH convention, *MRtrix3* now has more detailed documentation:
https://mrtrix.readthedocs.io/en/3.0.3/concepts/spherical_harmonics.html

I'll have to refamiliarise myself with this BEP and its branches before resolving this specific PR.

Regarding candidate proposal more generally, that's a larger discussion that will need to occur beyond this thread; I would suggest generating a Milestone and we can then add Issues to it as we think of them. Personally I think there's a lot more work needed before opening it up, but we can discuss the necessity of such on individual Issues.

**Comment by Lestropie** [comment]
Superseded by #27.

**Pull request closed without merging**
